-- POS Transaction Items for October 1-10, 2025
-- Insert statements for pos_transaction_items table
-- Note: IDs will be auto-generated by Supabase

INSERT INTO "public"."pos_transaction_items" (
  "transaction_id",
  "product_id",
  "product_name",
  "product_sku",
  "quantity",
  "unit_of_measure",
  "unit_price",
  "discount_amount",
  "discount_percentage",
  "line_total",
  "weight_kg",
  "expiry_date",
  "batch_number",
  "created_at"
) VALUES
-- October 1, 2025
-- TXN-20251001-083022: 2175.00
('8030b8cc-d1d7-4108-843c-c256da18bb90', '1981ce54-8390-4f13-afb4-222520b90906', 'B-MEG Integra 4000', 'FEED-001', 1.00, 'sack', 2175.00, 0.00, 0.00, 2175.00, null, null, null, '2025-10-01 08:30:22.000000+00'),

-- TXN-20251001-094518: 2190.00
('01f0edc6-f198-4068-b581-8ac9cb2680b4', '24c3ed39-401c-41d6-ad76-bcaf0a47f091', 'B-MEG Integra 3000 Plus (Poultry)', 'FEED-002', 1.00, 'sack', 2190.00, 0.00, 0.00, 2190.00, null, null, null, '2025-10-01 09:45:18.000000+00'),

-- TXN-20251001-133042: 4475.00
('8908c88f-3d8c-4b83-846b-8096326ea928', '1981ce54-8390-4f13-afb4-222520b90906', 'B-MEG Integra 4000', 'FEED-001', 1.00, 'sack', 2175.00, 0.00, 0.00, 2175.00, null, null, null, '2025-10-01 13:30:42.000000+00'),
('8908c88f-3d8c-4b83-846b-8096326ea928', '744802b6-10ea-403c-8542-a9c563327d18', 'Broiler Starter Crumble', 'FEED-008', 1.00, 'sack', 2300.00, 0.00, 0.00, 2300.00, null, null, null, '2025-10-01 13:30:42.000000+00'),

-- TXN-20251001-161525: 2500.00
('e3e93b09-1512-456d-bd38-3ef6f1538838', 'd1e961c4-4f0a-47ea-8717-9172d24629ad', 'Broiler Finisher Crumble', 'FEED-009', 1.00, 'sack', 2500.00, 0.00, 0.00, 2500.00, null, null, null, '2025-10-01 16:15:25.000000+00'),

-- October 2, 2025
-- TXN-20251002-091125: 2100.00
('393e9101-144a-4146-b086-b1e6af62a157', 'dc2dd3b2-2da1-41d2-8ef7-540dfbf3f753', 'Pigrolac Vital Hog Grower', 'FEED-011', 1.00, 'sack', 2100.00, 0.00, 0.00, 2100.00, null, null, null, '2025-10-02 09:11:25.000000+00'),

-- TXN-20251002-104532: 6640.00
('d1b4bffd-8655-46f8-b54e-5435aa0642d6', '1981ce54-8390-4f13-afb4-222520b90906', 'B-MEG Integra 4000', 'FEED-001', 1.00, 'sack', 2175.00, 0.00, 0.00, 2175.00, null, null, null, '2025-10-02 10:45:32.000000+00'),
('d1b4bffd-8655-46f8-b54e-5435aa0642d6', '744802b6-10ea-403c-8542-a9c563327d18', 'Broiler Starter Crumble', 'FEED-008', 1.00, 'sack', 2300.00, 0.00, 0.00, 2300.00, null, null, null, '2025-10-02 10:45:32.000000+00'),
('d1b4bffd-8655-46f8-b54e-5435aa0642d6', '3b3dd92a-b569-4914-9257-472389beff43', 'B-MEG Integra 3000', 'FEED-003', 1.00, 'sack', 2250.00, 0.00, 0.00, 2165.00, null, null, null, '2025-10-02 10:45:32.000000+00'),

-- TXN-20251002-142158: 1900.00
('a73d7659-9cb5-43b2-a61f-6486ec5d8c67', '17bcaa7b-4123-4e85-bb3d-35a66d0640bd', 'Hog Starter Pellet', 'FEED-006', 1.00, 'sack', 1900.00, 0.00, 0.00, 1900.00, null, null, null, '2025-10-02 14:21:58.000000+00'),

-- TXN-20251002-155845: 2250.00
('078099ba-6264-4b3e-a9dd-4a3106b0af4f', '3b3dd92a-b569-4914-9257-472389beff43', 'B-MEG Integra 3000', 'FEED-003', 1.00, 'sack', 2250.00, 0.00, 0.00, 2250.00, null, null, null, '2025-10-02 15:58:45.000000+00'),

-- October 3, 2025
-- TXN-20251003-082145: 2160.00
('054013bf-a9be-4604-b1a4-39635ff6f233', 'cf394640-89f4-441f-9707-05b60a79bc54', 'Pigrolac Vital Hog Finisher', 'FEED-012', 1.00, 'sack', 2160.00, 0.00, 0.00, 2160.00, null, null, null, '2025-10-03 08:21:45.000000+00'),

-- TXN-20251003-111532: 4375.00
('d0510b4f-c9b4-408f-a07d-33e56b129c0d', '1981ce54-8390-4f13-afb4-222520b90906', 'B-MEG Integra 4000', 'FEED-001', 1.00, 'sack', 2175.00, 0.00, 0.00, 2175.00, null, null, null, '2025-10-03 11:15:32.000000+00'),
('d0510b4f-c9b4-408f-a07d-33e56b129c0d', '24c3ed39-401c-41d6-ad76-bcaf0a47f091', 'B-MEG Integra 3000 Plus (Poultry)', 'FEED-002', 1.00, 'sack', 2190.00, 0.00, 0.00, 2200.00, null, null, null, '2025-10-03 11:15:32.000000+00'),

-- TXN-20251003-134521: 1135.00
('6d1bcc2c-dd33-4024-bc41-21826930b163', 'ce5fb47d-d041-4460-ba18-d61cc3f95455', 'B-MEG Integra 2500', 'FEED-005', 1.00, 'sack', 1135.00, 0.00, 0.00, 1135.00, null, null, 'BN-2025-001', '2025-10-03 13:45:21.000000+00'),

-- TXN-20251003-162308: 4600.00
('a95c7cea-add7-4b75-b62e-88aec2122196', '744802b6-10ea-403c-8542-a9c563327d18', 'Broiler Starter Crumble', 'FEED-008', 2.00, 'sack', 2300.00, 0.00, 0.00, 4600.00, null, null, null, '2025-10-03 16:23:08.000000+00'),

-- October 4, 2025
-- TXN-20251004-093258: 2190.00
('2c229c94-fc1d-492e-8347-600b7bdd2520', '24c3ed39-401c-41d6-ad76-bcaf0a47f091', 'B-MEG Integra 3000 Plus (Poultry)', 'FEED-002', 1.00, 'sack', 2190.00, 0.00, 0.00, 2190.00, null, null, null, '2025-10-04 09:32:58.000000+00'),

-- TXN-20251004-121445: 1800.00
('8095e049-ecf7-4313-99c6-18d837e8faf3', '2ca4cc05-7c96-4e0e-8818-75238ed630d2', 'Hog Grower Pellet', 'FEED-007', 1.00, 'sack', 1800.00, 0.00, 0.00, 1800.00, null, null, null, '2025-10-04 12:14:45.000000+00'),

-- TXN-20251004-143621: 5000.00 (with 200.00 discount = 4800.00)
('4796b976-b2f7-448d-ac13-7ed70410caee', '1981ce54-8390-4f13-afb4-222520b90906', 'B-MEG Integra 4000', 'FEED-001', 1.00, 'sack', 2175.00, 87.00, 4.00, 2088.00, null, null, null, '2025-10-04 14:36:21.000000+00'),
('4796b976-b2f7-448d-ac13-7ed70410caee', '744802b6-10ea-403c-8542-a9c563327d18', 'Broiler Starter Crumble', 'FEED-008', 1.00, 'sack', 2300.00, 92.00, 4.00, 2208.00, null, null, null, '2025-10-04 14:36:21.000000+00'),
('4796b976-b2f7-448d-ac13-7ed70410caee', 'd1e961c4-4f0a-47ea-8717-9172d24629ad', 'Broiler Finisher Crumble', 'FEED-009', 1.00, 'sack', 2500.00, 100.00, 4.00, 2400.00, null, null, null, '2025-10-04 14:36:21.000000+00'),

-- TXN-20251004-165032: 2300.00
('d22d4f07-a258-41ab-a8ac-d5944505d3ac', '744802b6-10ea-403c-8542-a9c563327d18', 'Broiler Starter Crumble', 'FEED-008', 1.00, 'sack', 2300.00, 0.00, 0.00, 2300.00, null, null, null, '2025-10-04 16:50:32.000000+00'),

-- October 5, 2025
-- TXN-20251005-081532: 2100.00
('cefa1edd-d1b9-4c8b-a843-ed54567b56f0', 'dc2dd3b2-2da1-41d2-8ef7-540dfbf3f753', 'Pigrolac Vital Hog Grower', 'FEED-011', 1.00, 'sack', 2100.00, 0.00, 0.00, 2100.00, null, null, null, '2025-10-05 08:15:32.000000+00'),

-- TXN-20251005-102145: 127.00
('8c4c91ef-5607-4327-80f5-05a108a4b298', 'e27b1411-96d2-4985-b63e-4f0e002fb57e', 'B-MEG Super Biik Booster + Milk Formula', 'FEED-004', 1.00, 'bag', 127.00, 0.00, 0.00, 127.00, null, null, null, '2025-10-05 10:21:45.000000+00'),

-- TXN-20251005-133258: 4475.00
('e0fdcc07-8971-47d7-80d4-78da19981e0f', '1981ce54-8390-4f13-afb4-222520b90906', 'B-MEG Integra 4000', 'FEED-001', 1.00, 'sack', 2175.00, 0.00, 0.00, 2175.00, null, null, null, '2025-10-05 13:32:58.000000+00'),
('e0fdcc07-8971-47d7-80d4-78da19981e0f', '744802b6-10ea-403c-8542-a9c563327d18', 'Broiler Starter Crumble', 'FEED-008', 1.00, 'sack', 2300.00, 0.00, 0.00, 2300.00, null, null, null, '2025-10-05 13:32:58.000000+00'),

-- TXN-20251005-151021: 6575.00
('e71308b3-742c-402f-bbe8-8546a05b822c', '1981ce54-8390-4f13-afb4-222520b90906', 'B-MEG Integra 4000', 'FEED-001', 1.00, 'sack', 2175.00, 0.00, 0.00, 2175.00, null, null, null, '2025-10-05 15:10:21.000000+00'),
('e71308b3-742c-402f-bbe8-8546a05b822c', '744802b6-10ea-403c-8542-a9c563327d18', 'Broiler Starter Crumble', 'FEED-008', 1.00, 'sack', 2300.00, 0.00, 0.00, 2300.00, null, null, null, '2025-10-05 15:10:21.000000+00'),
('e71308b3-742c-402f-bbe8-8546a05b822c', 'd1e961c4-4f0a-47ea-8717-9172d24629ad', 'Broiler Finisher Crumble', 'FEED-009', 1.00, 'sack', 2500.00, 0.00, 0.00, 2500.00, null, null, null, '2025-10-05 15:10:21.000000+00'),

-- October 6, 2025
-- TXN-20251006-085645: 2175.00
('93d08426-aca9-428d-a768-bf1b888d5214', '1981ce54-8390-4f13-afb4-222520b90906', 'B-MEG Integra 4000', 'FEED-001', 1.00, 'sack', 2175.00, 0.00, 0.00, 2175.00, null, null, null, '2025-10-06 08:56:45.000000+00'),

-- TXN-20251006-112532: 2190.00
('b0ba934c-d654-4b88-aa51-228f51e399d0', '24c3ed39-401c-41d6-ad76-bcaf0a47f091', 'B-MEG Integra 3000 Plus (Poultry)', 'FEED-002', 1.00, 'sack', 2190.00, 0.00, 0.00, 2190.00, null, null, null, '2025-10-06 11:25:32.000000+00'),

-- TXN-20251006-144521: 4275.00
('5f80e9fb-7076-4ebb-9a31-3c0d0aacf667', '1981ce54-8390-4f13-afb4-222520b90906', 'B-MEG Integra 4000', 'FEED-001', 1.00, 'sack', 2175.00, 0.00, 0.00, 2175.00, null, null, null, '2025-10-06 14:45:21.000000+00'),
('5f80e9fb-7076-4ebb-9a31-3c0d0aacf667', '24c3ed39-401c-41d6-ad76-bcaf0a47f091', 'B-MEG Integra 3000 Plus (Poultry)', 'FEED-002', 1.00, 'sack', 2190.00, 0.00, 0.00, 2100.00, null, null, null, '2025-10-06 14:45:21.000000+00'),

-- TXN-20251006-161258: 2800.00
('f383e2d6-3886-4a02-b322-47faf9e02ed9', '7aaa91a0-cc82-4e9b-90cb-0ef2eeb2c604', 'Pigrolac Early Wean Immunobooster', 'FEED-013', 1.00, 'sack', 2800.00, 0.00, 0.00, 2800.00, null, null, null, '2025-10-06 16:12:58.000000+00'),

-- October 7, 2025
-- TXN-20251007-092158: 2250.00
('1652f3c9-a1f2-4fb2-9e77-6da9c3a810a2', '3b3dd92a-b569-4914-9257-472389beff43', 'B-MEG Integra 3000', 'FEED-003', 1.00, 'sack', 2250.00, 0.00, 0.00, 2250.00, null, null, null, '2025-10-07 09:21:58.000000+00'),

-- TXN-20251007-113445: 4360.00
('5df23f62-97db-485e-bd74-d386505c7664', '24c3ed39-401c-41d6-ad76-bcaf0a47f091', 'B-MEG Integra 3000 Plus (Poultry)', 'FEED-002', 1.00, 'sack', 2190.00, 0.00, 0.00, 2190.00, null, null, null, '2025-10-07 11:34:45.000000+00'),
('5df23f62-97db-485e-bd74-d386505c7664', 'cf394640-89f4-441f-9707-05b60a79bc54', 'Pigrolac Vital Hog Finisher', 'FEED-012', 1.00, 'sack', 2160.00, 0.00, 0.00, 2170.00, null, null, null, '2025-10-07 11:34:45.000000+00'),

-- TXN-20251007-142532: 2160.00
('99b59871-0e60-45b8-8155-b01d32388e59', 'cf394640-89f4-441f-9707-05b60a79bc54', 'Pigrolac Vital Hog Finisher', 'FEED-012', 1.00, 'sack', 2160.00, 0.00, 0.00, 2160.00, null, null, null, '2025-10-07 14:25:32.000000+00'),

-- TXN-20251007-163021: 6250.00 (with 250.00 discount = 6000.00)
('dc674d0b-c205-42c1-aeae-751976bb4189', '1981ce54-8390-4f13-afb4-222520b90906', 'B-MEG Integra 4000', 'FEED-001', 1.00, 'sack', 2175.00, 87.00, 4.00, 2088.00, null, null, null, '2025-10-07 16:30:21.000000+00'),
('dc674d0b-c205-42c1-aeae-751976bb4189', '744802b6-10ea-403c-8542-a9c563327d18', 'Broiler Starter Crumble', 'FEED-008', 1.00, 'sack', 2300.00, 92.00, 4.00, 2208.00, null, null, null, '2025-10-07 16:30:21.000000+00'),
('dc674d0b-c205-42c1-aeae-751976bb4189', 'd1e961c4-4f0a-47ea-8717-9172d24629ad', 'Broiler Finisher Crumble', 'FEED-009', 1.00, 'sack', 2500.00, 100.00, 4.00, 2400.00, null, null, null, '2025-10-07 16:30:21.000000+00'),

-- October 8, 2025
-- TXN-20251008-084532: 1900.00
('f383c3d2-605f-489a-81ac-6b104951b055', '17bcaa7b-4123-4e85-bb3d-35a66d0640bd', 'Hog Starter Pellet', 'FEED-006', 1.00, 'sack', 1900.00, 0.00, 0.00, 1900.00, null, null, null, '2025-10-08 08:45:32.000000+00'),

-- TXN-20251008-111258: 2300.00
('32ef0c49-402f-44ba-8df8-498777114b9e', '744802b6-10ea-403c-8542-a9c563327d18', 'Broiler Starter Crumble', 'FEED-008', 1.00, 'sack', 2300.00, 0.00, 0.00, 2300.00, null, null, null, '2025-10-08 11:12:58.000000+00'),

-- TXN-20251008-134521: 2100.00
('736d1663-8871-48b1-a896-b096966e1e3e', 'dc2dd3b2-2da1-41d2-8ef7-540dfbf3f753', 'Pigrolac Vital Hog Grower', 'FEED-011', 1.00, 'sack', 2100.00, 0.00, 0.00, 2100.00, null, null, null, '2025-10-08 13:45:21.000000+00'),

-- TXN-20251008-152145: 1135.00
('7546f7e5-1ae5-497c-989e-18642b95ad97', 'ce5fb47d-d041-4460-ba18-d61cc3f95455', 'B-MEG Integra 2500', 'FEED-005', 1.00, 'sack', 1135.00, 0.00, 0.00, 1135.00, null, null, 'BN-2025-001', '2025-10-08 15:21:45.000000+00'),

-- October 9, 2025
-- TXN-20251009-091532: 2190.00
('b4459b3b-d4f3-4ffd-ab2f-38d7681228b2', '24c3ed39-401c-41d6-ad76-bcaf0a47f091', 'B-MEG Integra 3000 Plus (Poultry)', 'FEED-002', 1.00, 'sack', 2190.00, 0.00, 0.00, 2190.00, null, null, null, '2025-10-09 09:15:32.000000+00'),

-- TXN-20251009-114258: 2500.00
('91c8058d-0b87-4abd-be56-97de411e5169', 'd1e961c4-4f0a-47ea-8717-9172d24629ad', 'Broiler Finisher Crumble', 'FEED-009', 1.00, 'sack', 2500.00, 0.00, 0.00, 2500.00, null, null, null, '2025-10-09 11:42:58.000000+00'),

-- TXN-20251009-140845: 4600.00
('57af63e6-34e4-4f2d-9a2c-c5bac517dd43', '744802b6-10ea-403c-8542-a9c563327d18', 'Broiler Starter Crumble', 'FEED-008', 2.00, 'sack', 2300.00, 0.00, 0.00, 4600.00, null, null, null, '2025-10-09 14:08:45.000000+00'),

-- TXN-20251009-161532: 1800.00
('eb931ac9-862e-4525-9b41-0516dad02449', '2ca4cc05-7c96-4e0e-8818-75238ed630d2', 'Hog Grower Pellet', 'FEED-007', 1.00, 'sack', 1800.00, 0.00, 0.00, 1800.00, null, null, null, '2025-10-09 16:15:32.000000+00'),

-- October 10, 2025
-- TXN-20251010-083021: 2175.00
('01cadf43-e298-4088-a766-8efcfcdd08e6', '1981ce54-8390-4f13-afb4-222520b90906', 'B-MEG Integra 4000', 'FEED-001', 1.00, 'sack', 2175.00, 0.00, 0.00, 2175.00, null, null, null, '2025-10-10 08:30:21.000000+00'),

-- TXN-20251010-102445: 2250.00
('4bc085b7-a78c-4d03-b920-97bf3240622f', '3b3dd92a-b569-4914-9257-472389beff43', 'B-MEG Integra 3000', 'FEED-003', 1.00, 'sack', 2250.00, 0.00, 0.00, 2250.00, null, null, null, '2025-10-10 10:24:45.000000+00'),

-- TXN-20251010-131532: 4360.00
('90e791d1-2b44-4c0c-83c8-aeb48f998fd7', '24c3ed39-401c-41d6-ad76-bcaf0a47f091', 'B-MEG Integra 3000 Plus (Poultry)', 'FEED-002', 1.00, 'sack', 2190.00, 0.00, 0.00, 2190.00, null, null, null, '2025-10-10 13:15:32.000000+00'),
('90e791d1-2b44-4c0c-83c8-aeb48f998fd7', 'cf394640-89f4-441f-9707-05b60a79bc54', 'Pigrolac Vital Hog Finisher', 'FEED-012', 1.00, 'sack', 2160.00, 0.00, 0.00, 2170.00, null, null, null, '2025-10-10 13:15:32.000000+00'),

-- TXN-20251010-154258: 2100.00
('424e3fa6-71ae-472e-9daa-c5736100d894', 'dc2dd3b2-2da1-41d2-8ef7-540dfbf3f753', 'Pigrolac Vital Hog Grower', 'FEED-011', 1.00, 'sack', 2100.00, 0.00, 0.00, 2100.00, null, null, null, '2025-10-10 15:42:58.000000+00'),

-- TXN-20251010-171445: 4275.00
('a63162ca-b1e5-43ee-b3fc-6a89dd038f53', '1981ce54-8390-4f13-afb4-222520b90906', 'B-MEG Integra 4000', 'FEED-001', 1.00, 'sack', 2175.00, 0.00, 0.00, 2175.00, null, null, null, '2025-10-10 17:14:45.000000+00'),
('a63162ca-b1e5-43ee-b3fc-6a89dd038f53', '24c3ed39-401c-41d6-ad76-bcaf0a47f091', 'B-MEG Integra 3000 Plus (Poultry)', 'FEED-002', 1.00, 'sack', 2190.00, 0.00, 0.00, 2100.00, null, null, null, '2025-10-10 17:14:45.000000+00');

-- Summary: Transaction items for 40 transactions (October 1-10, 2025)
-- Note: Some transactions have multiple items
-- Items with batch_number: B-MEG Integra 2500 (BN-2025-001)
-- Items with discounts: TXN-20251004-143621 and TXN-20251007-163021
-- All items use sack unit except B-MEG Super Biik Booster (bag)

